@startuml design

!theme bluegray
skinparam classFontColor darkSlateGray
skinparam interface {
  BackgroundColor white
  BorderColor black
}

package "replication" {
  [replication-ctl:\nCLI Rust client] <-up-> [replication-image:\nPython gRPC messaging service and Replicate client]
}
interface "\t\t\tReplicate" as Replicate
[replication-image:\nPython gRPC messaging service and Replicate client] <--right--> Replicate

interface "\t\t\tIntent message" as Intent
[replication-ctl:\nCLI Rust client] <--right-- Intent

@enduml