@startuml design

!theme bluegray
skinparam classFontColor darkSlateGray
skinparam interface {
  BackgroundColor white
  BorderColor black
}

package "replication" {
  [replication-ctl:\nCLI Rust client] <-up-> [replication:\nPython gRPC messaging service and OpenAI client] : PDF data\nover gRPC
}
interface "\t\t\tOpenAI\n\t\t\tvia\n\t\t\tLlamaIndex" as OpenAI
[replication:\nPython gRPC messaging service and OpenAI client] <--right--> OpenAI

interface "\t\t\tPDF with\n\t\t\ttabular data" as PDF
[replication-ctl:\nCLI Rust client] <--right-- PDF

@enduml