[package]
name = "replication-ctl"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = "4.4.11"
image = "0.25.1"
prost = "0.12.3"
reqwest = "0.12.4"
tokio = { version = "1.27.0", features = ["full"] }
tonic = "0.11.0"

[build-dependencies]
tonic-build = "0.11.0"
